version: '3.6'
services:
  webapp:
    build: ./webapp
    ports:
      - 8002:80
      # - 443:443
    volumes:
      - ./webapp/sites-available /etc/apache2/sites-available
      - ./www:/var/www/html
    env_file:
      - .env
  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - ./www:/app
  mysql:
    image: mysql
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/mysql-data:/var/lib/mysql
      - ./mysql/init:/tmp/database-init
    restart: always
    command: mysqld --init-file="/tmp/database-init/init.sql"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env
  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - mysql:mysql
    ports:
      - 8001:80
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
      UPLOAD_LIMIT: 300M
    volumes:
      - /sessions
      - ./webapp/php.ini:/usr/local/etc/php/php.ini