name: Backend heroku deploy
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Add backend remote origin
      run: |
        git remote add heroku-backend https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
    - name: Create temporary subtree branch
      run: |
        git subtree split --prefix www HEAD -b deployHeroku
    - name: Deploy backend to Heroku
      run: |
        git push heroku-backend deployHeroku:master --force
    - name: Remove temp branch
      run: |
        git branch -D deployHeroku