name: PHP ftp to pohodnik tk
on:
  push:
    branches: [ master ]
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.1.0
      with:
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.0
      with:
        ftp-server: ftp://ftp.fednik.ru/
        ftp-username: deploy@pohodnik.tk
        ftp-password: ${{ secrets.FTP_PASS }}
        local-dir: ./www/pohodnik.tk 
        git-ftp-args: --remote-root /
